### ISSUE TITLE
No audio & unable to skip

### ISSUE THREAD

**Issue by PotatoParser** [ocf/jukebox#1]
While queuing the music, I noticed that there was no audio being played and when I tried to skip the current song, nothing happened.

@BernardZhao identified the bug as a connection loss in mpd.

![Screenshot (247)](https://user-images.githubusercontent.com/45542237/75600489-bcdc3900-5a64-11ea-964f-d9277784fe9a.png)

**Comment by BernardZhao** [comment]
Should be fixed with #3. If this happens again, we can reopen this issue. Usually when nothing is responsive either the client - server, server - mpd connection is broken.
