### ISSUE TITLE
Volume option is broken

### ISSUE THREAD

**Issue by PotatoParser** [ocf/jukebox#7]
It's literally broken.

**Comment by BernardZhao** [comment]
After investigation, I've discovered this isn't strictly because the control is broken, but the mpd setup on tornado literally doesn't have volume control, which is probably a pulseaudio / mpd setup issue. This needs to be set up properly per https://github.com/ocf/puppet/issues/887.

**Comment by encadyma** [comment]
Updated mpd.conf on tornado to use pulseaudio instead and volume is working now.
